import {
  AuditPolicy,
  changedOnly,
  hashed,
  nestedObject,
  relationshipIds,
  scalar,
} from '../types/audit-policy.types';
import { AuditResourceType } from '@/config/audit-events.config';

export const IDENTITY_AUDIT_POLICIES: Readonly<Record<string, AuditPolicy>> = {
  [AuditResourceType.IDENTITY_USER]: {
    id: scalar,
    identity: nestedObject({ email: changedOnly, password: changedOnly }),
    profile: nestedObject({
      id: scalar,
      name: nestedObject({ first: scalar, last: scalar }),
    }),
    roles: relationshipIds,
    status: nestedObject({ id: scalar, name: scalar }),
    active: scalar,
    created_at: scalar,
    updated_at: scalar,
    deleted_at: scalar,
    metadata: nestedObject({ mfa_enabled: changedOnly }),
  },
  [AuditResourceType.IDENTITY_PROFILE]: {
    id: scalar,
    name: nestedObject({ first: scalar, last: scalar, preferred: scalar }),
    first_name: scalar,
    last_name: scalar,
    preferred_name: scalar,
    biography: scalar,
    gender_id: scalar,
    country_id: scalar,
    timezone_id: scalar,
    avatar_id: scalar,
    date_of_birth: changedOnly,
  },
  [AuditResourceType.IDENTITY_PHONE]: {
    id: scalar,
    country_id: changedOnly,
    calling_code: changedOnly,
    national_number: changedOnly,
    e164: changedOnly,
  },
  [AuditResourceType.IDENTITY_ADDRESS]: {
    id: scalar,
    address_line_1: changedOnly,
    address_line_2: changedOnly,
    city: changedOnly,
    region_id: changedOnly,
    postal_code: changedOnly,
    country_id: changedOnly,
  },
  [AuditResourceType.IDENTITY_IMAGE]: {
    id: scalar,
    filename: scalar,
    mime_type: scalar,
    size_bytes: scalar,
    width: scalar,
    height: scalar,
  },
  [AuditResourceType.IDENTITY_SESSION]: {
    id: scalar,
    user_id: scalar,
    active: scalar,
    ip: hashed,
    user_agent: changedOnly,
    created_at: scalar,
    expires_at: scalar,
    revoked_at: scalar,
  },
  [AuditResourceType.IDENTITY_ROLE]: {
    id: scalar,
    name: scalar,
    active: scalar,
  },
  [AuditResourceType.IDENTITY_ACCOUNT_STATUS]: {
    id: scalar,
    name: scalar,
    active: scalar,
  },
};
